# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-2meRoYlFEJNTeHTB6TyIIjTq6LCoZgK
"""

import os
import bs4
import base64
import requests
import streamlit as st
from gtts import gTTS
from io import BytesIO

# LangChain components
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain_community.document_loaders import UnstructuredURLLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory

# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    page_title="Star Health Insurance AI Assistant",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom injection for a clean, professional, and accessible look
st.markdown("""
    <style>
    .main { background-color: #f8fafc; }
    .stButton>button {
        background-color: #0284c7;
        color: white;
        border-radius: 8px;
        border: none;
        padding: 0.5rem 1rem;
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        background-color: #0369a1;
        transform: translateY(-1px);
    }
    .sample-q {
        background-color: #ffffff;
        border-left: 4px solid #0284c7;
        padding: 10px 15px;
        margin: 8px 0;
        border-radius: 0 8px 8px 0;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
        cursor: pointer;
    }
    .header-container {
        background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 100%);
        color: white;
        padding: 2.5rem;
        border-radius: 12px;
        margin-bottom: 2rem;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 2. SIDEBAR PANEL (Configuration & Data Engine)
# ==========================================
with st.sidebar:
    st.image("https://algatesinsurance.in/wp-content/uploads/2025/04/Understanding-Domiciliary-Hospitalisation-in-Health-Insurance-1024x1024.png", width=200)
    st.title("Control Panel")
    st.markdown("---")

    # Secure API Entry
    openai_api_key = st.text_input(
        "OpenAI API Key",
        type="password",
        placeholder="sk-...",
        help="Provide your OpenAI key to access embedding models and execution layers."
    )

    st.markdown("### 📚 Knowledge Base Source")
    data_source_url = "https://www.starhealth.in/health-insurance/types-of-health-insurance/"
    st.caption(f"Default Target: {data_source_url}")

    st.markdown("### 🎙️ Audio Settings")
    enable_tts = st.checkbox("Enable Text-to-Speech (Read Out Aloud)", value=True)

    st.markdown("---")
    st.markdown("### 💡 Sample Queries")
    samples = [
        "What are different Maternity Health Insurance Plan in StarHealth?",
        "What benefits do Health Insurance policies offer?",
        "Why should you get a Health Insurance policy when you’re young?",
        "How many types of health insurance policies are there?",
        "What are the different types of health insurance schemes in India?"
    ]

    st.info("💡 **Tip:** Copy any sample question directly into the conversation dashboard below.")
    for idx, sample in enumerate(samples):
        st.markdown(f"**Q{idx+1}:** {sample}")

# ==========================================
# 3. CORE LOGIC / RAG INITIALIZATION ENGINE
# ==========================================
@st.cache_resource(show_spinner=False)
def initialize_rag_system(api_key, url):
    """Downloads content, splits into chunks, creates semantic embeddings, and initializes Chroma DB."""
    try:
        # Step 1: Document Fetching
        loader = UnstructuredURLLoader(urls=[url])
        documents = loader.load()

        # Step 2: Content Splitting
        text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
        chunks = text_splitter.split_documents(documents)

        # Step 3: Vectorization & Storage
        embeddings = OpenAIEmbeddings(openai_api_key=api_key)
        vectorstore = Chroma.from_documents(chunks, embeddings)
        return vectorstore.as_retriever(search_kwargs={"k": 4})
    except Exception as e:
        st.error(f"Failed to process RAG Pipeline: {str(e)}")
        return None

# ==========================================
# 4. MAIN USER INTERFACE PRESENTATION
# ==========================================
st.markdown("""
    <div class="header-container">
        <h1 style='margin:0;'>🏥 Star Health Insurance Guidance Assistant</h1>
        <p style='margin:5px 0 0 0; opacity:0.8; font-size:1.1rem;'>
            Context-Aware RAG Prototype Powered by LangChain, Chroma DB & OpenAI
        </p>
    </div>
""", unsafe_allow_html=True)

# Validation Wall
if not openai_api_key:
    st.warning("⚠️ Please provide a valid OpenAI API Key in the left sidebar configuration window to begin.")
    st.stop()

# Initialize the vector engine
with st.spinner("Analyzing knowledge manuals and preparing vector indexing configurations..."):
    retriever = initialize_rag_system(openai_api_key, data_source_url)

if retriever is None:
    st.error("RAG setup encountered an unexpected failure. Verify your endpoint network or parsing properties.")
    st.stop()

# Setup Core Chat State Store
if "chat_history" not in st.session_state:
    st.session_state.chat_history = ChatMessageHistory()

if "messages" not in st.session_state:
    st.session_state.messages = []

# Display interactive dialog panels
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        if "audio" in message and enable_tts:
            st.audio(message["audio"], format="audio/mp3")

# ==========================================
# 5. DIALOG PROCESSING LOOP
# ==========================================
if user_query := st.chat_input("Ask me about insurance policies, coverage parameters, or benefits..."):

    # 1. Print Query to View Screen
    with st.chat_message("user"):
        st.markdown(user_query)
    st.session_state.messages.append({"role": "user", "content": user_query})

    # 2. Extract Document Context via Vector DB
    retrieved_docs = retriever.invoke(user_query)
    context_blob = "\n\n".join([doc.page_content for doc in retrieved_docs])

    # 3. Assemble Conversational Chain Models
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", "You are an expert context-aware assistant for Star Health Insurance. "
                   "Provide clear, informative, and precise guidance to patients using the extracted "
                   "knowledge base details. If the answer cannot be confidently deduced from the text manual, "
                   "advise the user to contact Star Health Support directly.\n\n"
                   "Manual Context Extracts:\n{context}"),
        MessagesPlaceholder(variable_name="history"),
        ("human", "{question}")
    ])

    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.3, openai_api_key=openai_api_key)
    brain_chain = prompt_template | llm

    # Wrap with contextual message history constraints
    conversational_agent = RunnableWithMessageHistory(
        brain_chain,
        lambda session_id: st.session_state.chat_history,
        input_messages_key="question",
        history_messages_key="history"
    )

    # 4. Process Generation Request
    with st.chat_message("assistant"):
        with st.spinner("Reviewing insurance documentation frameworks..."):
            response = conversational_agent.invoke(
                {"context": context_blob, "question": user_query},
                config={"configurable": {"session_id": "default_user_session"}}
            )
            response_text = response.content
            st.markdown(response_text)

            # 5. Process Integrated Audio Generation Engine (TTS)
            message_store = {"role": "assistant", "content": response_text}

            if enable_tts:
                try:
                    tts = gTTS(text=response_text, lang='en', slow=False)
                    audio_buffer = BytesIO()
                    tts.write_to_fp(audio_buffer)
                    audio_bytes = audio_buffer.getvalue()

                    st.audio(audio_bytes, format="audio/mp3")
                    message_store["audio"] = audio_bytes
                except Exception as audio_err:
                    st.caption("🔊 Audio synthesis engine encountered formatting delays.")

            st.session_state.messages.append(message_store)
